global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [alertmanager:9093]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: ez-kafka
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ez-kafka:8080]
