spring:
  application:
    name: ez-kafka
  docker:
    compose:
      enabled: false
  kafka:
    consumer:
      bootstrap-servers: ${PIM_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: ${random.uuid}
      security:
        protocol: SSL
      ssl:
        bundle: ez-kafka

  ssl:
    bundle:
      jks:
        ez-kafka:
          truststore:
            type: PKCS12
            location: classpath:truststore.p12
            password: changeit
          keystore:
            type: PKCS12
            location: classpath:keystore.p12
            password: changeit

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}